version: '3.4'

services:
  greeter:
    image: ${DOCKER_REGISTRY-}greeter
    build:
      context: .
      dockerfile: E:/src/rdl/xplat-netcore-webassembly/src/02-services/Greeter/Dockerfile

  sandwichmaker:
    image: ${DOCKER_REGISTRY-}sandwichmaker
    build:
      context: .
      dockerfile: E:/src/rdl/xplat-netcore-webassembly/src/02-services/SandwichMaker/Dockerfile

  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: E:/src/rdl/xplat-netcore-webassembly/src/02-services/Gateway/Dockerfile
