version: '3.4'

services:
  greeter:
    image: ${DOCKER_REGISTRY-}greeter
    build:
      context: .
      dockerfile: Greeter/Dockerfile

  sandwichmaker:
    image: ${DOCKER_REGISTRY-}sandwichmaker
    build:
      context: .
      dockerfile: SandwichMaker/Dockerfile

  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile

  meatservice:
    image: ${DOCKER_REGISTRY-}meatservice
    build:
      context: .
      dockerfile: MeatService/Dockerfile

  breadservice:
    image: ${DOCKER_REGISTRY-}breadservice
    build:
      context: .
      dockerfile: BreadService/Dockerfile

  cheeseservice:
    image: ${DOCKER_REGISTRY-}cheeseservice
    build:
      context: .
      dockerfile: CheeseService/Dockerfile

  lettuceservice:
    image: ${DOCKER_REGISTRY-}lettuceservice
    build:
      context: .
      dockerfile: LettuceService/Dockerfile

