version: '3.4'

services:
  greeter:
    image: ${DOCKER_REGISTRY-}greeter
    build:
      context: .
      dockerfile: Greeter/Dockerfile

  sandwichmaker:
    image: ${DOCKER_REGISTRY-}sandwichmaker
    build:
      context: .
      dockerfile: SandwichMaker/Dockerfile
    environment: 
      - RABBITMQ__URL
      - RABBITMQ__USER
      - RABBITMQ__PASSWORD

  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    environment: 
      - RABBITMQ__URL
      - RABBITMQ__USER
      - RABBITMQ__PASSWORD

  meatservice:
    image: ${DOCKER_REGISTRY-}meatservice
    build:
      context: .
      dockerfile: MeatService/Dockerfile
    environment: 
      - RABBITMQ__URL
      - RABBITMQ__USER
      - RABBITMQ__PASSWORD

  breadservice:
    image: ${DOCKER_REGISTRY-}breadservice
    build:
      context: .
      dockerfile: BreadService/Dockerfile
    environment: 
      - RABBITMQ__URL
      - RABBITMQ__USER
      - RABBITMQ__PASSWORD

  cheeseservice:
    image: ${DOCKER_REGISTRY-}cheeseservice
    build:
      context: .
      dockerfile: CheeseService/Dockerfile
    environment: 
      - RABBITMQ__URL
      - RABBITMQ__USER
      - RABBITMQ__PASSWORD

  lettuceservice:
    image: ${DOCKER_REGISTRY-}lettuceservice
    build:
      context: .
      dockerfile: LettuceService/Dockerfile
    environment: 
      - RABBITMQ__URL
      - RABBITMQ__USER
      - RABBITMQ__PASSWORD

