apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter
spec:
  selector:
    matchLabels:
      app: greeter
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
      - name: greeter
        image: rdlk8s.azurecr.io/greeter:v1
        env:
        - name: RABBITMQ__URL
          value: dinky-wallaby-rabbitmq