apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandwichmaker
spec:
  selector:
    matchLabels:
      app: sandwichmaker
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: sandwichmaker
    spec:
      containers:
      - name: sandwichmaker
        image: rdlk8s.azurecr.io/sandwichmaker:v1
        env:
        - name: RABBITMQ__URL
          value: dinky-wallaby-rabbitmq